version: "3.9"
services:
  db:
    restart: always
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_PORT: $DB_PORT
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
      args:
        DEBUG: ${BE_DEBUG}
    depends_on:
      - db
    ports:
      - "${BE_PORT}:${BE_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend:/backend

  frontend:
    build:
      context: .
      dockerfile: config/frontend.Dockerfile
      args:
        FE_CMD: ${FE_CMD}
    depends_on:
      - web
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public
    ports:
      - "${FE_PORT}:${FE_PORT}"
    env_file:
      - .env

volumes:
  db:
    driver: local
