"""Add user to patient

Revision ID: 04a8e272b5f0
Revises: 924985e23b07
Create Date: 2023-01-05 16:55:25.319592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a8e272b5f0'
down_revision = '924985e23b07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###
