"""Add unique constraints to user

Revision ID: 4af8040a1ba7
Revises: dcc0d8c23bb0
Create Date: 2022-09-21 11:59:53.357525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4af8040a1ba7"
down_revision = "dcc0d8c23bb0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
