"""Added appointment model

Revision ID: 924985e23b07
Revises: a998fb6c5a6a
Create Date: 2022-09-30 17:06:36.200136

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "924985e23b07"
down_revision = "a998fb6c5a6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appointments_id"), "appointments", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointments_id"), table_name="appointments")
    op.drop_table("appointments")
    # ### end Alembic commands ###
