"""Create Patient model

Revision ID: a998fb6c5a6a
Revises: 4af8040a1ba7
Create Date: 2022-09-26 14:23:29.717350

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a998fb6c5a6a"
down_revision = "4af8040a1ba7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_email"), "patients", ["email"], unique=True)
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_email"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
