"""Added name to appointments

Revision ID: aaadd534696e
Revises: 04a8e272b5f0
Create Date: 2023-01-05 18:26:22.888346

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aaadd534696e"
down_revision = "04a8e272b5f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointments", "name")
    # ### end Alembic commands ###
