name: Continuous Integration

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: |
          cd backend
          poetry install
      - name: Formatters
        run: |
          cd backend
          poetry run black . --check
          poetry run isort . -c
      - name: Linters
        run: |
          cd backend
          poetry run mypy .
          poetry run flake8 .
          poetry run pylint app/
      - name: Tests
        run: |
          cd backend
          poetry run pytest .
