name: Continuous Integration

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      SECRET_KEY: SomeSecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 5
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          poetry install

      - name: Formatters
        run: |
          cd backend
          poetry run black . --check
          poetry run isort . -c

      - name: Linters
        run: |
          cd backend
          poetry run mypy .
          poetry run flake8 .
          poetry run pylint app/
